-- CreateTable
CREATE TABLE "MAE_Descuentos" (
    "ID_DESCUENTO" SERIAL NOT NULL,
    "DESCRIPCION" VARCHAR(100) NOT NULL,
    "MONTO" DECIMAL(10,2),
    "PORCENTAJE" INTEGER,
    "ID_DESCUENTO_TRANSACCIONAL" INTEGER,

    CONSTRAINT "MAE_Descuentos_pkey" PRIMARY KEY ("ID_DESCUENTO")
);

-- CreateTable
CREATE TABLE "MAE_Empleado" (
    "ID_EMPLEADO" SERIAL NOT NULL,
    "ID_TIPO" INTEGER,
    "NOMBRE" VARCHAR(100) NOT NULL,
    "APELLIDO" VARCHAR(100) NOT NULL,
    "FECHA_NACIMIENTO" DATE NOT NULL,
    "HIJOS" VARCHAR(3) NOT NULL,
    "DIRECCION" VARCHAR(200) NOT NULL,
    "FECHA_INGRESO" DATE NOT NULL,
    "ID_EMPRESA" VARCHAR(20),
    "DOCUMENTO" VARCHAR(20),

    CONSTRAINT "MAE_Empleado_pkey" PRIMARY KEY ("ID_EMPLEADO")
);

-- CreateTable
CREATE TABLE "MAE_Empresa" (
    "ID_EMPRESA" VARCHAR(20) NOT NULL,
    "RAZON_SOCIAL" VARCHAR(100),
    "RUBRO_EMPRESA" VARCHAR(100),
    "DIRECCION" VARCHAR(200),
    "RUC" VARCHAR(11),
    "NOMBRE" VARCHAR(100),

    CONSTRAINT "MAE_Empresa_pkey" PRIMARY KEY ("ID_EMPRESA")
);

-- CreateTable
CREATE TABLE "MAE_Remuneraciones" (
    "ID_REMUNERACIONES" SERIAL NOT NULL,
    "DESCRIPCION" VARCHAR(100) NOT NULL,
    "MONTO" DECIMAL(10,2) NOT NULL,
    "ID_REMUNERACION_TRANSACCIONAL" INTEGER,

    CONSTRAINT "MAE_Remuneraciones_pkey" PRIMARY KEY ("ID_REMUNERACIONES")
);

-- CreateTable
CREATE TABLE "MAE_Tipo_Documento" (
    "ID_TIPO" SERIAL NOT NULL,
    "DESCRIPCION" VARCHAR(100),

    CONSTRAINT "MAE_Tipo_Documento_pkey" PRIMARY KEY ("ID_TIPO")
);

-- CreateTable
CREATE TABLE "TRS_Aportaciones" (
    "ID_APORTACIONES" SERIAL NOT NULL,
    "ESSALUD" DECIMAL(10,2) NOT NULL,
    "SCTR" DECIMAL(10,2) NOT NULL,

    CONSTRAINT "TRS_Aportaciones_pkey" PRIMARY KEY ("ID_APORTACIONES")
);

-- CreateTable
CREATE TABLE "TRS_Boleta_Pago" (
    "ID_BOLETA_PAGO" SERIAL NOT NULL,
    "FECHA" DATE NOT NULL,
    "ID_EMPLEADO" INTEGER NOT NULL,
    "DIAS_LABORADOS" INTEGER NOT NULL,
    "TOTAL_HORAS_LABORADAS" DECIMAL(10,2) NOT NULL,
    "DIAS_NO_LABORADOS" INTEGER,
    "HORAS_EXTRAS" DECIMAL(10,2),
    "NETO_PAGAR" DECIMAL(10,2) NOT NULL,
    "ID_BOLETA_PAGO_DETALLES" INTEGER,
    "MES" INTEGER,

    CONSTRAINT "TRS_Boleta_Pago_pkey" PRIMARY KEY ("ID_BOLETA_PAGO")
);

-- CreateTable
CREATE TABLE "TRS_Boleta_Pago_Detalle" (
    "ID_BOLETA_PAGO_DETALLE" SERIAL NOT NULL,
    "ID_DESCUENTO_TRANSACCIONAL" INTEGER,
    "ID_REMUNERACION_TRANSACCIONAL" INTEGER,
    "ID_APORTACIONES_TRANSACCIONAL" INTEGER,

    CONSTRAINT "TRS_Boleta_Pago_Detalle_pkey" PRIMARY KEY ("ID_BOLETA_PAGO_DETALLE")
);

-- CreateTable
CREATE TABLE "TRS_Descuentos" (
    "ID_DESCUENTO_TRANSACCIONAL" SERIAL NOT NULL,
    "TOTAL" DECIMAL(10,2) NOT NULL,

    CONSTRAINT "TRS_Descuentos_pkey" PRIMARY KEY ("ID_DESCUENTO_TRANSACCIONAL")
);

-- CreateTable
CREATE TABLE "TRS_Remuneraciones" (
    "ID_REMUNERACION_TRANSACCIONAL" SERIAL NOT NULL,
    "TOTAL" DECIMAL(10,2) NOT NULL,

    CONSTRAINT "TRS_Remuneraciones_pkey" PRIMARY KEY ("ID_REMUNERACION_TRANSACCIONAL")
);

-- AddForeignKey
ALTER TABLE "MAE_Descuentos" ADD CONSTRAINT "MAE_Descuentos_ID_DESCUENTO_TRANSACCIONAL_fkey" FOREIGN KEY ("ID_DESCUENTO_TRANSACCIONAL") REFERENCES "TRS_Descuentos"("ID_DESCUENTO_TRANSACCIONAL") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "MAE_Empleado" ADD CONSTRAINT "MAE_Empleado_ID_EMPRESA_fkey" FOREIGN KEY ("ID_EMPRESA") REFERENCES "MAE_Empresa"("ID_EMPRESA") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "MAE_Empleado" ADD CONSTRAINT "MAE_Empleado_ID_TIPO_fkey" FOREIGN KEY ("ID_TIPO") REFERENCES "MAE_Tipo_Documento"("ID_TIPO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "MAE_Remuneraciones" ADD CONSTRAINT "MAE_Remuneraciones_ID_REMUNERACION_TRANSACCIONAL_fkey" FOREIGN KEY ("ID_REMUNERACION_TRANSACCIONAL") REFERENCES "TRS_Remuneraciones"("ID_REMUNERACION_TRANSACCIONAL") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "TRS_Boleta_Pago" ADD CONSTRAINT "TRS_Boleta_Pago_ID_BOLETA_PAGO_DETALLES_fkey" FOREIGN KEY ("ID_BOLETA_PAGO_DETALLES") REFERENCES "TRS_Boleta_Pago_Detalle"("ID_BOLETA_PAGO_DETALLE") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "TRS_Boleta_Pago" ADD CONSTRAINT "TRS_Boleta_Pago_ID_EMPLEADO_fkey" FOREIGN KEY ("ID_EMPLEADO") REFERENCES "MAE_Empleado"("ID_EMPLEADO") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "TRS_Boleta_Pago_Detalle" ADD CONSTRAINT "TRS_BOLETA_PAGO_DETALLE_ID_APORTACIONES_TRANSACCIONAL_fkey" FOREIGN KEY ("ID_APORTACIONES_TRANSACCIONAL") REFERENCES "TRS_Aportaciones"("ID_APORTACIONES") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "TRS_Boleta_Pago_Detalle" ADD CONSTRAINT "TRS_BOLETA_PAGO_DETALLE_ID_DESCUENTO_TRANSACCIONAL_fkey" FOREIGN KEY ("ID_DESCUENTO_TRANSACCIONAL") REFERENCES "TRS_Descuentos"("ID_DESCUENTO_TRANSACCIONAL") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "TRS_Boleta_Pago_Detalle" ADD CONSTRAINT "TRS_BOLETA_PAGO_DETALLE_ID_REMUNERACION_TRANSACCIONAL_fkey" FOREIGN KEY ("ID_REMUNERACION_TRANSACCIONAL") REFERENCES "TRS_Remuneraciones"("ID_REMUNERACION_TRANSACCIONAL") ON DELETE NO ACTION ON UPDATE NO ACTION;
